### ISSUE TITLE
Get last song

### ISSUE THREAD

**Issue by zVerox** [nepodev/lautfm#4]
Hello,
do you have an example for me on how to get the last song?

**Comment by nepodev** [comment]
Hi,

you have to use `getStation(<stationname>, 'last_songs')` with value 'last_songs' for the param section.

example with stationname "skaworld"
```js

const laut = new Lautfm();
laut.getStation('skaworld', 'last_songs')
    .then(console.log)
    .catch(console.error)
```

You will receive an array with song objects.
http://api.laut.fm/station/skaworld/last_songs
